# Generated by Django 4.0 on 2021-12-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учители',
            },
        ),
        migrations.CreateModel(
            name='TimeGr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Время кружка')),
            ],
            options={
                'verbose_name': 'Время',
                'verbose_name_plural': 'Время',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование комнаты')),
                ('content', models.TextField(blank=True, verbose_name='Комментария')),
                ('is_published', models.BooleanField(default=True, verbose_name='Занята')),
                ('teachers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rooms.teachers', verbose_name='Учитель')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rooms.timegr', verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
    ]
